import Link from "next/link";

export const metadata = { title: "Community — help shape MiniKit", description: "Bring a small software problem, test a free tool, or contribute a focused solution. Help shape MiniKit's next useful tool." };
const issues = "https://github.com/RadimStud/tinytools/issues";

export default function CommunityPage() {
  return <main className="min-h-screen bg-neutral-950 px-5 py-10 text-neutral-100"><div className="mx-auto max-w-5xl">
    <nav className="flex flex-wrap justify-between gap-4 text-sm"><Link href="/" className="font-semibold">← MiniKit</Link><a href={issues} className="text-emerald-300">Open community board ↗</a></nav>
    <header className="my-16 max-w-3xl"><p className="text-xs uppercase tracking-widest text-emerald-300">Small tools. Shared ideas.</p><h1 className="mt-5 text-4xl font-semibold tracking-tight sm:text-6xl">Bring a problem.<br /><span className="text-emerald-300">Help shape a tool.</span></h1><p className="mt-6 text-lg leading-8 text-neutral-400">MiniKit is early. We are starting with small, focused tools and real feedback from the people who use them. You do not need to write code to take part.</p></header>
    <section className="grid gap-4 md:grid-cols-3" aria-label="Ways to participate">
      {[
        { number: "01", title: "Try a tool", text: "Clean a sample CSV, then tell us what was confusing or what would save you time.", href: "/workbench/csv-cleaner", cta: "Try CSV Cleaner" },
        { number: "02", title: "Bring a use case", text: "Describe your task, the workaround you use today and the result you want. Made-up examples are welcome.", href: `${issues}/new?template=tool-idea.yml`, cta: "Suggest a tool on GitHub" },
        { number: "03", title: "Make it better", text: "Report a reproducible bug, improve instructions, or propose one small, testable contribution.", href: `${issues}/new?template=bug-report.yml`, cta: "Report a problem" },
      ].map(card => <article key={card.number} className="flex flex-col rounded-2xl border border-neutral-800 bg-neutral-900/40 p-6"><span className="font-mono text-sm text-emerald-300">/{card.number}</span><h2 className="mt-6 text-xl font-semibold">{card.title}</h2><p className="mb-6 mt-3 text-sm leading-6 text-neutral-400">{card.text}</p><Link className="mt-auto text-sm font-medium text-emerald-300" href={card.href}>{card.cta} →</Link></article>)}
    </section>
    <p className="mt-5 text-sm text-neutral-400">GitHub participation needs a GitHub account and is public. Prefer a simple suggestion form? <Link href="/request" className="text-emerald-300 underline">Request a tool here</Link>. Form submissions are not posted to the public board.</p>
    <section className="mt-16 border-t border-neutral-800 pt-8"><h2 className="text-2xl font-semibold">What happens to an idea?</h2><ol className="mt-6 grid gap-6 text-sm text-neutral-400 sm:grid-cols-3"><li><strong className="mb-2 block text-neutral-100">1. Describe the task</strong>Explain the input, desired output and how often you face the problem.</li><li><strong className="mb-2 block text-neutral-100">2. Compare experiences</strong>Add your use case to an existing issue. Specific examples help more than a vote alone.</li><li><strong className="mb-2 block text-neutral-100">3. Test a small solution</strong>Ideas are proposals, not delivery promises. When an implementation is ready, its pull request shows the changes and checks.</li></ol></section>
    <section className="mt-14 grid gap-8 sm:grid-cols-2"><div><h2 className="text-xl font-semibold">Current direction</h2><ul className="mt-4 space-y-3 text-sm text-neutral-400"><li><span className="text-emerald-300">Available:</span> free browser-based CSV cleaning.</li><li><span className="text-emerald-300">Available:</span> a marketplace for downloadable tools.</li><li><span className="text-neutral-200">Exploring:</span> text comparison, JSON utilities and better file workflows, guided by concrete requests.</li></ul></div><div><h2 className="text-xl font-semibold">A useful, respectful space</h2><p className="mt-4 text-sm leading-6 text-neutral-400">Discuss the problem, not the person. No spam or unsolicited promotion. Use synthetic examples; do not post passwords, customer records or confidential files.</p><a href="https://github.com/RadimStud/tinytools/blob/main/CONTRIBUTING.md" className="mt-4 inline-block text-sm text-emerald-300">Contribution guide ↗</a></div></section>
    <footer className="mt-16 flex flex-wrap justify-between gap-4 border-t border-neutral-800 py-6 text-sm text-neutral-500"><span>Built one useful tool at a time.</span><a href="https://github.com/RadimStud/tinytools" className="text-neutral-300">Follow development on GitHub ↗</a></footer>
  </div></main>;
}
